name: Cloudformation nag
on: [push]
#on: 
#  pull_request:target:
#    branches:
#     - main  
# Este ON se usa cuando necesita allguna acciones muy especifica, como por ejemplo aca
# que te pide que se activo solo cuado se haga un pullrequest a main.
jobs:
    cloudformation-nag:

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            - run: brew install ruby brew-gem
            - run: brew gem install cfn-nag 
